# the config of all browser-use
backend:
  # basic web service config
  host: localhost # backend host
  port: 9000 # backend port
  secure-key: DEMO_EKY # secure key of  backend

  # agent config
  agent-type: agentscope # now support agentscope, to add more
  llm-name: qwen-max # llm name, support qwen-max, qwen-turbo, qwen-plus, for more details, read dashscope document.
  agent-timeout: 3600 # agent timeout, unit: second

  # session history service, it supports three modes: none, memory, redis.
  # none means no session service used
  # memory means the session history will be stored in memory
  # redis means the session history will be stored in redis
  session-type: none # session type, support memory, redis (you need install redis)
  session-redis: # config this if you use redis as session store
    url: redis://localhost:6379/0

  # memory service, it supports three modes: none, memory, redis
  # none means no memory service used
  # memory means the memory will be stored in memory
  # redis means the memory will be stored in redis
  memory-type: none # memory type, support none, memory, redis
  memory-redis: # config this if you use redis as memory store
    url: redis://localhost:6379/0

  # sandbox service, it supports two modes (local and remote)
  # local means use local docker to run sandbox
  # remote means use remote sandbox to run sandbox
  sandbox-type:  local # sandbox type, support local and remote
  sandbox-remote:
    url: http://xx.xx.xx.xx:xx # set your sandbox url
frontend:
  # basic front-end config
  host: localhost # frontend host
  port: 3000 # frontend port.
