[project]
name = "agentscope-runtime"
version = "0.1.3"
description = "A production-ready runtime framework for agent applications, providing secure sandboxed execution environments and scalable deployment solutions with multi-framework support."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.8.0,<1.10.0",
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "openai",
    "pydantic>=2.11.7",
    "requests>=2.32.4",
]

[tool.setuptools]
packages = { find = { where = ["src"] } }

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
runtime-sandbox-mcp = "agentscope_runtime.sandbox.mcp_server:main"
runtime-sandbox-server = "agentscope_runtime.sandbox.manager.server.app:main"
runtime-sandbox-builder = "agentscope_runtime.sandbox.build:main"

[project.optional-dependencies]
dev = [
    "pytest>=8.3.5",
    "pytest-asyncio>=0.23.0",
    "pre-commit>=4.2.0",
    "jupyter-book>=1.0.4.post1",
    "furo>=2025.7.19",
    "pytest-cov>=6.2.1",
    "fakeredis>=2.31.0",
    "sphinx-autoapi>=3.6.0",
]

sandbox = [
    "docker>=7.1.0",
    "steel-sdk>=0.1.0",
    "redis>=6.0.0b2",
    "oss2>=2.19.1",
    "pydantic-settings>=2.9.1",
    "dotenv>=0.9.9",
    "kubernetes>=33.1.0",
    "shortuuid>=1.0.13",
]

agentscope = [
    "agentscope==1.0.0",
]

langgraph = [
    "langgraph>=0.5.3",
]

agno = [
    "agno>=1.7.5,<2.0.0",
]
a2a = [
    "a2a-sdk>=0.3.0",
]
autogen = [
    "autogen-agentchat>=0.7.4",
    "autogen-ext[openai]>=0.7.4",
]

langchain_rag=[
    "langchain>=0.3.25",
    "pymilvus>=2.6.0",
    "langchain-community>=0.3.27",
    "langchain-milvus>=0.2.1",
]